export const demo_tree_data = {
  root: {
    type: "root",
    id: "root",
    props: {},
    options: {},
    children: ["s1", "s2", "s3"],
  },
  s1: {
    type: "section",
    id: "s1",
    props: { className: "mi-max-w-5xl mi-mx-auto mi-p-4" },
    options: {},
    children: ["row11"],
  },
  row11: {
    type: "row",
    id: "row11",
    props: { className: "mi-p-4" },
    options: {},
    children: ["col111"],
  },
  col111: {
    type: "column",
    id: "col111",
    props: { className: "mi-relative mi-w-full" },
    options: {},
    children: ["h11"],
  },
  h11: {
    type: "h1",
    id: "h11",
    props: { className: "mi-text-xl mi-text-green-500" },
    options: {},
    children: ["t11"],
  },
  t11: {
    type: "text-node",
    id: "t11",
    children: "Heading 1",
  },
  s2: {
    type: "section",
    id: "s2",
    props: { className: "/mi-max-w-5xl mi-mx-auto mi-p-4" },
    options: {},
    children: ["row12"],
  },
  row12: {
    type: "row",
    id: "row12",
    props: { className: "mi-p-4" },
    options: {},
    children: ["col121"],
  },
  col121: {
    type: "column",
    id: "col121",
    props: { className: "mi-relative mi-w-full" },
    options: {},
    children: ["h12"],
  },
  h12: {
    type: "h1",
    id: "h12",
    props: { className: "mi-text-xl mi-text-blue-500" },
    options: {},
    children: ["t12"],
  },
  t12: {
    type: "text-node",
    id: "t12",
    children: "Heading 2",
  },
  s3: {
    type: "section",
    id: "s3",
    props: { className: "mi-max-w-5xl mi-mx-auto mi-p-4" },
    options: {},
    children: ["row13"],
  },
  row13: {
    type: "row",
    id: "row13",
    props: { className: "mi-flex mi-flex-col sm:mi-flex-row /mi-p-4" },
    options: {},
    children: ["col131", "col132"],
  },
  col131: {
    type: "column",
    id: "col131",
    props: { className: "mi-relative mi-w-full" },
    options: {},
    children: ["h13"],
  },
  h13: {
    type: "h1",
    id: "h13",
    props: { className: "mi-text-xl mi-text-blue-500" },
    options: {},
    children: ["t131"],
  },
  t131: {
    type: "text-node",
    id: "t131",
    children: "Heading 3: 1",
  },
  col132: {
    type: "column",
    id: "col132",
    props: { className: "mi-relative mi-w-full" },
    options: {},
    children: ["h23"],
  },
  h23: {
    type: "h1",
    id: "h23",
    props: { className: "mi-text-xl mi-text-blue-500" },
    options: {},
    children: ["t132"],
  },
  t132: {
    type: "text-node",
    id: "t132",
    children: "Heading 3: 2",
  },
};
